language: node_js
node_js:
        - "12"
os:
        - linux
        - osx
dist: bionic
jobs:
        include:
                - os: linux
                  arch: amd64
                  env: OS=linux-amd64
                - os: osx
                  arch: amd64
                  env: OS=darwin-amd64
script:
        - if [ -d node_modules/ ]; then rm -rf ./node_modules/; fi
        - npm ci
        - npm run protoc-build
        - if [ "$OS" = "linux-amd64" ]; then npm run pkg-build-binary-linux-amd64; fi
        - if [ "$OS" = "darwin-amd64" ]; then npm run pkg-build-binary-darwin-amd64; fi
deploy:
        - provider: releases
          file:
                  - ./.bin/math-grpc-node-server-linux-amd64
                  - ./.bin/math-grpc-node-server-darwin-amd64
                  - ./.bin/grpc_node.node-linux-amd64
                  - ./.bin/grpc_node.node-darwin-amd64
          api_key:
                  secure: TmP5Xl+Cg7bCSOX/ra4eOWif1O1B3sP0RRW0NW69TMQNgRtalfCchZJyEW0XauUH5Qcsq03s+TTp0jb3C5U7FKXkl/C5rkdh825yBCREtVmy6r9J0lZHSMej0WabHg5ccCY9KDZbSHWw1kxOfPihIJqjEcUai5mKXebjN9ynPXcWvywSMGx0YSy9YeVaTrIRn4o4XQbwxJ4fzhCQJKev/fljsO0B85O2fIXcb7BToyHll8/BF3k0AmjfLQMmoguGoD3K4BI5ZS5YRYb2bCsZsJx1NYdjTQlLzsOVUEIXlg6x1kh9wb1+BUTyrKwxe7MyoMz7lLvx8iSbvCA7PZVlst9bfCgmxn0KtAIyTNV9NE5tYKYjdBmOOJ4Slg549KVX4EAvPeCf7R5RGuL7++Yvc08/tCNno4J86M38Hq8BLQhbH601y+PCG7MkT8v8ahz65az/yBXGCd7adMHIaIQG6ANorZvZTp1NOf7kQ0b3EPMs4qaVzdeVUkt2RGmbT2kNwmltZfEQv1btgLUjxZZf6RN8ASqQ9hqmahWSZhH6g1CEF8zmDI+Kpz3Ufz3SA06Z0jgE/RRqHSnZsa0Usl+i8sjfL1kRDVGGeAfppI6oEc5djVJtgkP/B9ZgDiBmUzryo8+ORRuDnNp0GWSKrKD7GY1NZp66g122Rj8wIWIdmkY=
          on:
                  repo: pojntfx/mather.js
                  all_branches: true
          skip_cleanup: true
        - provider: npm
          email: felicitas@pojtinger.com
          api_key:
                  secure: TvFIM5q5pdlsuF6GeYn8tekevGeJJiKvGyFX2OarmrQmqoFW4D2EiBqw8BPKgNnSI6mtPjKXO2tbfiGSHQg0i4xfq58Po/cH3TpdyfeQpzZdivm4wJQbo7waGj7wTTs6bkrEaRT4gFcTG6lU3cMnquEm7BXIXgsZAmeKgukLbKyH+eq6VRKMW6opS6ILfqopGHGS4xeas1ESRv1dontuVMRl09PiLlYb9SW8JBQ/V6DjnYSg31MQw4Cn+HTevPA32NodR4IXKojotaOUGT6NsUn1B87JLcZn1sjk9mAlVWIYNkcoiVrdo1VX1sffs4MmWDliDSx8vqc8QlBY+XsIq5aWebmTep5xf+0CoUBkuTe83Uwz+nM2bxE6R9SwzShxZq0bOF2GD2X3EoAQ7zEhllLNowgvbWmIXZdUA4M+uFwb01p4MuHMLe3cKney6knsBPsCIvuPBQMlRjBBjN6Bgv2affUaERDSf283o4BJC/Z1F+LXS8vWm01l2OyHjfFioUcAg4XLqJOPCVobTq+0pj///xl9hNVgtLLldRmdQtzNHcHYRTqZnXfJhNA49RDgTTWCpdMnOAisugNWpny56NPhWBSmVIK5VdS1Y/Cy0nxxQTM3fEeWfev7HYkvpMZBeMqzDDvQIKPN/BY61/PHQaq6+1bYhkbzI5PVgZvG7lg=
          on:
                  repo: pojntfx/mather.js
                  all_branches: true
                  condition: $OS = linux-amd64 && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
          skip_cleanup: true
