sudo: required
language: node_js
dist: bionic
os:
  - linux
  - osx
node_js:
  - '12'
addons:
  apt:
    update: true
    packages:
      - wget
      - protobuf-compiler
  homebrew:
    update: true
    packages:
      - wget
      - protobuf
script:
  - npm run build-protoc
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then npm run build-pkg-linux-amd64; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm run build-pkg-darwin-amd64; fi
deploy:
  skip_cleanup: true
  provider: releases
  file:
    - ./.bin/math-grpc-node-server-linux-amd64
    - ./.bin/math-grpc-node-server-darwin-amd64
    - ./.bin/grpc_node.node-linux-amd64
    - ./.bin/grpc_node.node-darwin-amd64
  api_key:
    secure: TmP5Xl+Cg7bCSOX/ra4eOWif1O1B3sP0RRW0NW69TMQNgRtalfCchZJyEW0XauUH5Qcsq03s+TTp0jb3C5U7FKXkl/C5rkdh825yBCREtVmy6r9J0lZHSMej0WabHg5ccCY9KDZbSHWw1kxOfPihIJqjEcUai5mKXebjN9ynPXcWvywSMGx0YSy9YeVaTrIRn4o4XQbwxJ4fzhCQJKev/fljsO0B85O2fIXcb7BToyHll8/BF3k0AmjfLQMmoguGoD3K4BI5ZS5YRYb2bCsZsJx1NYdjTQlLzsOVUEIXlg6x1kh9wb1+BUTyrKwxe7MyoMz7lLvx8iSbvCA7PZVlst9bfCgmxn0KtAIyTNV9NE5tYKYjdBmOOJ4Slg549KVX4EAvPeCf7R5RGuL7++Yvc08/tCNno4J86M38Hq8BLQhbH601y+PCG7MkT8v8ahz65az/yBXGCd7adMHIaIQG6ANorZvZTp1NOf7kQ0b3EPMs4qaVzdeVUkt2RGmbT2kNwmltZfEQv1btgLUjxZZf6RN8ASqQ9hqmahWSZhH6g1CEF8zmDI+Kpz3Ufz3SA06Z0jgE/RRqHSnZsa0Usl+i8sjfL1kRDVGGeAfppI6oEc5djVJtgkP/B9ZgDiBmUzryo8+ORRuDnNp0GWSKrKD7GY1NZp66g122Rj8wIWIdmkY=
  on:
    repo: pojntfx/math-grpc-node
