language: node_js
node_js:
  - '12'

os:
  - linux
  - osx
dist: bionic

addons:
  apt:
    update: true
    packages:
      - wget
      - protobuf-compiler
  homebrew:
    update: true
    packages:
      - wget
      - protobuf

jobs:
  include:
    - os: linux
      arch: amd64
      env: OS=linux-amd64
      #    - os: linux
      #      arch: arm64
      #      env: OS=linux-arm64
    - os: osx
      arch: amd64
      env: OS=darwin-amd64

script:
  - npm run build-protoc
  - if [ "$OS" = "linux-amd64" ]; then npm run build-pkg-linux-amd64; fi
    #  - if [ "$OS" = "linux-arm64" ]; then npm run build-pkg-linux-arm64; fi
  - if [ "$OS" = "darwin-amd64" ]; then npm run build-pkg-darwin-amd64; fi
  - rm -rf ./node_modules/

deploy:
  cleanup: false
  provider: releases
  file:
    - ./.bin/math-grpc-node-server-linux-amd64
      #    - ./.bin/math-grpc-node-server-linux-arm64
    - ./.bin/math-grpc-node-server-darwin-amd64
    - ./.bin/grpc_node.node-linux-amd64
      #    - ./.bin/grpc_node.node-linux-arm64
    - ./.bin/grpc_node.node-darwin-amd64
  token:
    secure: TmP5Xl+Cg7bCSOX/ra4eOWif1O1B3sP0RRW0NW69TMQNgRtalfCchZJyEW0XauUH5Qcsq03s+TTp0jb3C5U7FKXkl/C5rkdh825yBCREtVmy6r9J0lZHSMej0WabHg5ccCY9KDZbSHWw1kxOfPihIJqjEcUai5mKXebjN9ynPXcWvywSMGx0YSy9YeVaTrIRn4o4XQbwxJ4fzhCQJKev/fljsO0B85O2fIXcb7BToyHll8/BF3k0AmjfLQMmoguGoD3K4BI5ZS5YRYb2bCsZsJx1NYdjTQlLzsOVUEIXlg6x1kh9wb1+BUTyrKwxe7MyoMz7lLvx8iSbvCA7PZVlst9bfCgmxn0KtAIyTNV9NE5tYKYjdBmOOJ4Slg549KVX4EAvPeCf7R5RGuL7++Yvc08/tCNno4J86M38Hq8BLQhbH601y+PCG7MkT8v8ahz65az/yBXGCd7adMHIaIQG6ANorZvZTp1NOf7kQ0b3EPMs4qaVzdeVUkt2RGmbT2kNwmltZfEQv1btgLUjxZZf6RN8ASqQ9hqmahWSZhH6g1CEF8zmDI+Kpz3Ufz3SA06Z0jgE/RRqHSnZsa0Usl+i8sjfL1kRDVGGeAfppI6oEc5djVJtgkP/B9ZgDiBmUzryo8+ORRuDnNp0GWSKrKD7GY1NZp66g122Rj8wIWIdmkY=
  on:
    repo: pojntfx/math-grpc-node
